/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntovtn;
import Db_Conexion.*;
import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingConstants;

public class Productos extends javax.swing.JFrame {
    private final Cm_Productos CP;
    double min = 0.00;
    double value = 0.00;
    double max = 9999.00;
    double stepSize = 0.10;
    SpinnerNumberModel model = new SpinnerNumberModel(value, min, max, stepSize);
    JSpinner spinner = new JSpinner(model);
    public Productos() {
        initComponents();
        CP =new Cm_Productos();
        jLabel3.setBackground(new Color(44, 62, 80));
        JSpinner.NumberEditor editor = (JSpinner.NumberEditor)spinner.getEditor();
        DecimalFormat format = editor.getFormat();
        format.setMinimumFractionDigits(2);
        editor.getTextField().setHorizontalAlignment(SwingConstants.CENTER);
        jPanel1.add(spinner);
        spinner.setBounds(190, 180, 80, 27);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Registro de Productos");
        setSize(new java.awt.Dimension(610, 323));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/productos-cosmeticos (1).png"))); // NOI18N
        jLabel3.setText("Productos");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 0, 610, 90);

        jPanel1.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Codigo de Producto:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 40, 120, 14);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(190, 40, 287, 27);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Descripción:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 80, 120, 20);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(190, 80, 290, 27);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Cantidad:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 130, 120, 20);
        jPanel1.add(jSpinner1);
        jSpinner1.setBounds(190, 130, 80, 27);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Precio:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 180, 120, 20);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(110, 240, 90, 23);

        jButton2.setText("Cancelar");
        jPanel1.add(jButton2);
        jButton2.setBounds(350, 240, 100, 23);

        jTabbedPane2.addTab("Registro", jPanel1);

        jPanel2.setLayout(null);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Codigo de Producto:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(70, 80, 120, 14);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(200, 80, 287, 20);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(jLabel8);
        jLabel8.setBounds(200, 120, 120, 20);
        jPanel2.add(jSpinner2);
        jSpinner2.setBounds(200, 160, 80, 20);

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(120, 210, 90, 23);

        jButton4.setText("Cancelar");
        jPanel2.add(jButton4);
        jButton4.setBounds(360, 210, 100, 23);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Cantidad:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(70, 160, 120, 20);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Cantidad:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(70, 120, 120, 20);

        jTabbedPane2.addTab("Agregar", jPanel2);

        getContentPane().add(jTabbedPane2);
        jTabbedPane2.setBounds(0, 60, 590, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String descripcion;
        String code;
        int cantidad;
        double precio;
        if(jTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Necesita Ingresar el Codigo de Barra o Plu","Ingrese Datos",JOptionPane.INFORMATION_MESSAGE);
            jTextField1.setFocusable(true);
        }else{
            code = jTextField1.getText();
            if(jTextField2.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Necesita Ingresar Descripción del Producto","Ingrese Datos",JOptionPane.INFORMATION_MESSAGE);
                jTextField2.setFocusable(true);
            }else{
                descripcion = jTextField2.getText();
                if((int)jSpinner1.getValue()>0){
                    cantidad = (int)jSpinner1.getValue();
                    precio= (double) spinner.getValue();
                    if(precio>0){
                        
                        CP.insertDatos(code, descripcion, cantidad, (float) precio);
                        this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(null,"Ingrese una Cantidad Mayor a 0","Ingrese Datos",JOptionPane.INFORMATION_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Ingrese una Cantidad Mayor a 0","Ingrese Datos",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
      
    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Panel.produc=null;
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
    char caracter = evt.getKeyChar();

      // Verificar si la tecla pulsada no es un digito
      if(((caracter < '0') ||
         (caracter > '9')) &&
         (caracter != '\b'))
      {
         evt.consume();  // ignorar el evento de teclado
      }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
